apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgCdJ82PCZHF0in2oxEHK3NjuWgMP+meTtQXUQ1oUpJUPQao5uuC5ursZAs+qCt1N08DhUUOJ2HPZHZrDWBbQgk6d05iGRTY3s++JigPLApriYNpqc5hkQcfz0sczyJmOAbg4NXvJD+CzPD3ztmEol5XjxNChWo2ENY2XRVz3z75pYSp6asa3AmQPE2/ZPaxSyLIGWHowXfZBFgC7FIgNlQwAZXQwGg4IJzaOpw/eLiodYUYOk/42foJr5IqpKdkxYwE8IR+FORpKsM1dy2c3wT2ZN4ai29nCKpOzfB2iBQgAnj/BTbJoCSxcqOaz7cwepeimfiDIrr1kAJXiHjWaJ/etbKskdvdSY92xiY5FPsBSFfsFJIvyA0WYEGu6fTope/UcwWmmDhrosQ5Mb/VaPC2V1dA+7WQtuQOLqXfsNkkQmXHvtVv40b70IFUclBANj3iuka6bNYggVsEYKWvJl+ii/BOSn0n3GSdzDH3KrZ3IrTcuErquvfW1sxwmXA0XqTRDzx8vwZ0pnX+hObsyFMS/06xohj2v3oI8NpUpHQ825+skEWYkpt+bw6Fiu7xFIq9tvJF+rZpw1p/oQDSpMz5hTtw06xMCcOriCX/p4ezSTNTYZcykQKeA96CRRs3Ohln7748Y2/eV8uwBcwQ+gvNfygf3zV0QmFqOeHnJECUgBnRI4ZoS95mcWDAWC6SGivjw3/gcGXEwe0bDGZC77gBVN983i76NKILTIqDLt/bV0/pImmTXj5x
    username: AgBLNSHf0xRDBNpbNyT7IS2tommXeseqC549MPfaz4COHWk3ZfZD1Favg046nNFkZ8ObXnQLLCAeAztvgxyGHqzh3tPQJHIu2Ss+sS0nk9IeD7a4LpddDQqYxokk2ETDeLPVc8+Ahy3wyeM14aL0gpM9JyidTk9IYJozB24yXK6IkqobcRJdsBfDMvhRriXDSVzU9QFOowgjFn9RxAr8gYq0VCGAl0RD50ACeCsuwa/5zv+me5ezxJma6exr/AfsIt8OX8PHGokxG47al5r595KgFPiaoglv5hZfTVVSy2IJB4hHZivTQFbq9my4aiFjAFms4DwhkFzjw/xG6hOzMHY+mnYqgDVY8bbbsK8wvbEyZZQ1GypkRVESr0TYs1LZv5qwi6iFWaiU3PxE25bAGC6FdOU3KYbk6s9tr0eOH94nTzDMxPzwoznXatA6lpJhrdZCHyUc0sv6hZ5h/B9OzPmk+1F5qGJuswpNJ1T3qjUwGAotGzKGWJNgHSRdDKvT4J4UN/SDY2mb6g9QmlQT3NYPe3kczl0GvbEjkuA8GQkVYnEm5X0xxfRz9KUBz9TMDtKtN4wfVjQKGBEIzRR3gfLjY9CSHjXLSrKiZ2+5CcQdNLBC15AJiE2UpOlxGPN+zTac23x2c63lo+J9CCgfMWCKnAXinLHTNXAq8EQz48g5FOZk8u+nSFwLzvPTTIUvAfSOclZwZkHT
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

