apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgAWV0XlTkd2oqY+SNa8ZW4SiGmF0mBxVNx+3vn39qWD6s8LYkyWGF68bVulqnsx4ae/ardB9wawRIGbLaANkzMj2WEomW/B/y51qHbT1Lzx3Fmrzb3thVvfUgbgmMyQSzDDqi6LMRP5xhNGyI8WUzZZQ00isNveykxTl0jQb6jYDHXWhgLFS1CpV1P3Ud29jA3FxzZxgHqhAXPV0ClOtlE6mH4e5tsYPHXlfktn1lcNAPblV04SS3TK8gZhXLspvV1FeBkFS3GT0RuA3SJ8o2Xcdd4+c6Kvhkr7iCHLMTbi1XYcTAPzgAD2Zfat33VPFOPeft9tamUkHui5nlllGajBWeSvgCE8UvuYIOgf4yOZnKyol7TtoFhBqI8eQOoYvtJlY0jsTpkOQtUfSFDDfVgwyQrqudMNhjHgcFRgRqmAHkmTF8X9fNhTDXR4NAJX2kJlInZkFYEOnGxtvTktTQrOstoCRdpMp4K1rYuV1XL3nVhGF6fTsJ1GadNKdCiCva9KnFCoaZ9uQkOV86iR2desd8ZTR8EcQDXZeLRtpI7aKUNOBQRZe7wroH67W0sWB3rr0qRaTBv2QdeAZAkyJ+boshOSWu9v8add80Vh1jOn8bLzv1gjiX+AkFLWWJdiXiBMDXSbKmcK8kl0HRuojtsj7QNeDANRFkLeTkOxN6cA0YfpFVRSRdBqq0oS0Y92vFGrYUlxdHGMInzrSeapphfVAdxEyGcV+dwtu4b24P5Pb1S/GVIkli1I
    username: AgANI+G8UuUo/3jUlWQsIv98DcAba1fjQiByDoeM9L5rWpyfZHVKZpV9TyK+ZYYubliAJlO7pYQKWxQuh2MWCMavFwKbJkZauvHy9IcGqjkmw6cg4i7RYdR5sC+z8MXcAvc+MOGKFejSi39ecGg/2DEULLqhTCnclgV3/ooCmdzQPPuY1ScTWpfOAbY+kRgZ4XhYvE07Npm8QFQiPjK2bUwHuh9bHosSsts+VUxYv3rfgo1ygqNbTlwHR0/YgUN27leFVsRV9mpm0XdDWtYkFkFWL/wV5W8lmfMQc913z5W98j1MkvwHkaCw1bY6eOZ4BC7Hb4pRhphGXBeiMZW6eChsDk3ElXG2ZYxXMaPL+Y+OFKKr0YSwTq3PLkKxcgYXwSWqoLf62/QMgtHape8Sx6IlE5GGdJz4uqlOk6UOeIPHIsEEYqJNTOf7skcCPIr6IgliJ5DKTlQnznLuU8DWLAr/evLjcgunQcY+b9rW9TZ53cuZIclQ++5fpmArSEWLYGURANeGzidv51h4F/FNsMFUUZQc2HMKkqKLA8Q69N6GjKibdFDc1ZCqYF03MIALu+9hy1P1ve/vJt0kbA+tL9wulFrCOhalNirLtYTQuk0pQ78gO6PgSm7eXrllEddXwypOohSD1FXnJmp4N0LYueMOXDsBoZMUmRkaHx4KSTQywPIEfyndsacnnZhyErBzY8+Qbnz6pnQS
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

